language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run lint
  - npm run test:unit
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: storybook-static
  on:
    branch: master
